[features]
seeds = false

[programs.localnet]
namaph_multisig = "A13BbQ3UV9CvermetyC5ymZN2gqCLTM8CqpwragH7kCX"
serum_multisig = "F13SUGwECtzuUWKUEFj1fS2ZgZSdiKNu7Wd86NHBStEb"

[programs.devnet]
namaph_multisig = "A13BbQ3UV9CvermetyC5ymZN2gqCLTM8CqpwragH7kCX"
serum_multisig = "F13SUGwECtzuUWKUEFj1fS2ZgZSdiKNu7Wd86NHBStEb"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/yasushi/.config/solana/test_id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
