[features]
seeds = false
[programs.localnet]
multisig_cpi = "9VtuF6VxDRjUMD1XVfLooYbdkuYwyLA8Us7P1uhYYutq"
serum_multisig = "BX8apctw1h5wnc12K39VEgjQT7pMMT1PY9NqaHD3K914"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/yasushi/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
