[features]
seeds = false

[programs.localnet]
namaph_multisig = "A13BbQ3UV9CvermetyC5ymZN2gqCLTM8CqpwragH7kCX"
serum_multisig = "F13SUGwECtzuUWKUEFj1fS2ZgZSdiKNu7Wd86NHBStEb"

[programs.devnet]
namaph_multisig = "A13BbQ3UV9CvermetyC5ymZN2gqCLTM8CqpwragH7kCX"
serum_multisig = "F13SUGwECtzuUWKUEFj1fS2ZgZSdiKNu7Wd86NHBStEb"

[programs.mainnet]
serum_multisig = "32GVEhxwPxBBNDpdvLzZiBEfE2221vKbJ7L8v7Zk39BF"
namaph_multisig = "58iucLiYSA1iNDG6Qo9jTWmRtk25Un3XLBDTyGhEeqHR"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/yasushi/.config/solana/test_id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy = "cp ./target/idl/*.json ./app/src/idl/ && cp ./target/idl/*.json ./util/src/idl/"
